model: "resnet_estimator"
env_variables:
  TF_ENABLE_BF16_CONVERSION: 1
  TF_ALLOW_CONTROL_EDGES_IN_HABANA_OPS: 1
  TF_PRELIMINARY_CLUSTER_SIZE: 200
  USE_LARS_OPTIMIZER: 1

parameters:
  num_gpus: 1
  data_dir: "/root/tensorflow_datasets/imagenet/tf_records"
  distribution_strategy: "off"
  data_format: "channels_last"
  save_checkpoint_steps: 5005
  batch_size: 256
  resnet_size: 50
  train_epochs: 40
  model_dir: "/tmp/resnet_estimator"
  display_steps: 100
  experimental_preloading: 1
  use_horovod: false
  use_train_and_evaluate: false
  epochs_between_evals: 8
  enable_lars: true
  dummy_epoch: false
  data_loader_image_type: "bf16"
  weight_decay: 0.0001
  label_smoothing: 0.1
  epochs_for_lars: 40
  start_learning_rate: 2.5
  warmup_epochs: 3
  train_offset: 0
  is_mlperf_enabled: false