model: "resnet_estimator"
env_variables:
  HBN_TF_REGISTER_DATASETOPS: 1
  TF_RECIPE_CACHE_PATH: "/tmp/resnet_estimator"
  LOG_LEVEL_ALL: 6

parameters:
  dtype: "bf16"
  data_dir: "/root/tensorflow_datasets/imagenet/tf_records"
  batch_size: 128
  train_epochs: 90
  model_dir: "/root/tmp/resnet_estimator"
  experimental_preloading: 1
  use_horovod: true
  num_workers_per_hls: 8