model: "resnet_keras"

env_variables:
  TF_ALLOW_CONTROL_EDGES_IN_HABANA_OPS: 1
  USE_LARS_OPTIMIZER: 1

parameters:
  data_dir: "/root/tensorflow_datasets/imagenet/tf_records"
  batch_size: 128
  steps_per_loop: 100
  log_steps: 100
  model_dir: "/root/tmp/resnet/"
  data_format: "channels_last"
  train_epochs: 90
  experimental_preloading: 1
  enable_checkpoint_and_export: false
  enable_tensorboard: true
  epochs_between_evals: 8
  use_horovod: true
  optimizer: "SGD"
  lr_schedule: "piecewise"
  data_loader_image_type: "fp32"
  weight_decay: 0.0001
  warmup_epochs: 5
  distribution_strategy: "off"
  num_gpus: 0
  num_workers_per_hls: 8